#! /bin/bash

#export BSPWM_PANEL_HIDE=1

nitrogen --restore
sxhkd &
~/.config/bspwm/panel &

bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d Main Term Text Web Media Misc

bspc rule -a Chromium desktop=Web
bspc rule -a Firefox desktop=Web
bspc rule -a MPlayer desktop=Media
bspc rule -a mpv desktop=Media
bspc rule -a Vlc desktop=Media
bspc rule -a URxvt desktop=Term
bspc rule -a Gnome-terminal desktop=Term
bspc rule -a Gvim desktop=Text
