#! /bin/sh

nitrogen --restore
sxhkd &
~/.config/bspwm/panel &

bspc config top_padding 20
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc monitor -d main term web media misc system


bspc rule -a Chromium desktop=^3
bspc rule -a Firefox desktop=^3
bspc rule -a MPlayer desktop=^4
bspc rule -a mpv desktop=^4
bspc rule -a Vlc desktop=^4
bspc rule -a URxvt desktop=^2
bspc rule -a Gnome-terminal desktop=^2
bspc rule -a Nautilus desktop=^1 follow=on
bspc rule -a Virtualbox desktop=^1 follow=on
